### ISSUE TITLE
Make installation is not working with v1.8

### ISSUE THREAD

**Issue by manabanana** [marbl/canu#1143]
Hi CANU devolopers, 
I am trying to install v1.8 from source due to the problem I was having with the binary of v1.8 (listed in issue #1138), but unfortuantely after 'make -j8', I see the Linux*/bin directories being created, but the bin directory is empty.   I'm able to install v1.7.1 from source without any problems though.  The output onto the screen is long, so below I have pasted the last part of the output, but if you need the whole output please let me know.  I would appreciate any suggestions on what I should change to install the program.  Thanks for the great assembler!  
 
```
make: *** [/home/u11/manabanana/bin/canu-1.8/Linux-amd64/obj/lib/libcanu.a/utility/libbacktrace/dwarf.o] Error 1
make: *** Waiting for unfinished jobs....
utility/libbacktrace/elf.c: In function ‘elf_add_syminfo_data’:
utility/libbacktrace/elf.c:450: error: ‘__ATOMIC_ACQUIRE’ undeclared (first use in this function)
utility/libbacktrace/elf.c:450: error: (Each undeclared identifier is reported only once
utility/libbacktrace/elf.c:450: error: for each function it appears in.)
utility/libbacktrace/elf.c: In function ‘elf_syminfo’:
utility/libbacktrace/elf.c:495: error: ‘__ATOMIC_ACQUIRE’ undeclared (first use in this function)
utility/libbacktrace/elf.c: In function ‘backtrace_initialize’:
utility/libbacktrace/elf.c:960: error: ‘__ATOMIC_RELEASE’ undeclared (first use in this function)
utility/libbacktrace/elf.c:975: error: ‘__ATOMIC_ACQUIRE’ undeclared (first use in this function)
make: *** [/home/u11/manabanana/bin/canu-1.8/Linux-amd64/obj/lib/libcanu.a/utility/libbacktrace/elf.o] Error 1
In file included from utgcns/libboost/boost/scoped_ptr.hpp:14:0,
                 from utgcns/libboost/boost/graph/adjacency_list.hpp:31,
                 from utgcns/libpbutgcns/AlnGraphBoost.H:69,
                 from utgcns/libcns/unitigConsensus.C:77:
utgcns/libboost/boost/smart_ptr/scoped_ptr.hpp:68:31: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     explicit scoped_ptr( std::auto_ptr<T> p ) BOOST_NOEXCEPT : px( p.release() )
                               ^~~~~~~~
In file included from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/memory:81:0,
                 from utgcns/libboost/boost/unordered/unordered_set_fwd.hpp:14,
                 from utgcns/libboost/boost/unordered/unordered_set.hpp:17,
                 from utgcns/libboost/boost/unordered_set.hpp:17,
                 from utgcns/libboost/boost/graph/adjacency_list.hpp:21,
                 from utgcns/libpbutgcns/AlnGraphBoost.H:69,
                 from utgcns/libcns/unitigConsensus.C:77:
/cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from utgcns/libboost/boost/smart_ptr/shared_ptr.hpp:28:0,
                 from utgcns/libboost/boost/shared_ptr.hpp:17,
                 from utgcns/libboost/boost/format/alt_sstream.hpp:21,
                 from utgcns/libboost/boost/format/internals.hpp:23,
                 from utgcns/libboost/boost/format.hpp:38,
                 from utgcns/libpbutgcns/AlnGraphBoost.C:72:
utgcns/libboost/boost/smart_ptr/detail/shared_count.hpp:395:33: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     explicit shared_count( std::auto_ptr<Y> & r ): pi_( new sp_counted_impl_p<Y>( r.get() ) )
                                 ^~~~~~~~
In file included from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/locale_conv.h:41:0,
                 from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/locale:43,
                 from utgcns/libboost/boost/format.hpp:23,
                 from utgcns/libpbutgcns/AlnGraphBoost.C:72:
/cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from utgcns/libboost/boost/shared_ptr.hpp:17:0,
                 from utgcns/libboost/boost/format/alt_sstream.hpp:21,
                 from utgcns/libboost/boost/format/internals.hpp:23,
                 from utgcns/libboost/boost/format.hpp:38,
                 from utgcns/libpbutgcns/AlnGraphBoost.C:72:
utgcns/libboost/boost/smart_ptr/shared_ptr.hpp:242:65: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
 template< class T, class R > struct sp_enable_if_auto_ptr< std::auto_ptr< T >, R >
                                                                 ^~~~~~~~
In file included from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/locale_conv.h:41:0,
                 from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/locale:43,
                 from utgcns/libboost/boost/format.hpp:23,
                 from utgcns/libpbutgcns/AlnGraphBoost.C:72:
/cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from utgcns/libboost/boost/shared_ptr.hpp:17:0,
                 from utgcns/libboost/boost/format/alt_sstream.hpp:21,
                 from utgcns/libboost/boost/format/internals.hpp:23,
                 from utgcns/libboost/boost/format.hpp:38,
                 from utgcns/libpbutgcns/AlnGraphBoost.C:72:
utgcns/libboost/boost/smart_ptr/shared_ptr.hpp:441:31: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     explicit shared_ptr( std::auto_ptr<Y> & r ): px(r.get()), pn()
                               ^~~~~~~~
In file included from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/locale_conv.h:41:0,
                 from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/locale:43,
                 from utgcns/libboost/boost/format.hpp:23,
                 from utgcns/libpbutgcns/AlnGraphBoost.C:72:
/cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from utgcns/libboost/boost/shared_ptr.hpp:17:0,
                 from utgcns/libboost/boost/format/alt_sstream.hpp:21,
                 from utgcns/libboost/boost/format/internals.hpp:23,
                 from utgcns/libboost/boost/format.hpp:38,
                 from utgcns/libpbutgcns/AlnGraphBoost.C:72:
utgcns/libboost/boost/smart_ptr/shared_ptr.hpp:454:22: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     shared_ptr( std::auto_ptr<Y> && r ): px(r.get()), pn()
                      ^~~~~~~~
In file included from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/locale_conv.h:41:0,
                 from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/locale:43,
                 from utgcns/libboost/boost/format.hpp:23,
                 from utgcns/libpbutgcns/AlnGraphBoost.C:72:
/cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from utgcns/libboost/boost/shared_ptr.hpp:17:0,
                 from utgcns/libboost/boost/format/alt_sstream.hpp:21,
                 from utgcns/libboost/boost/format/internals.hpp:23,
                 from utgcns/libboost/boost/format.hpp:38,
                 from utgcns/libpbutgcns/AlnGraphBoost.C:72:
utgcns/libboost/boost/smart_ptr/shared_ptr.hpp:520:34: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     shared_ptr & operator=( std::auto_ptr<Y> & r )
                                  ^~~~~~~~
In file included from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/locale_conv.h:41:0,
                 from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/locale:43,
                 from utgcns/libboost/boost/format.hpp:23,
                 from utgcns/libpbutgcns/AlnGraphBoost.C:72:
/cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from utgcns/libboost/boost/shared_ptr.hpp:17:0,
                 from utgcns/libboost/boost/format/alt_sstream.hpp:21,
                 from utgcns/libboost/boost/format/internals.hpp:23,
                 from utgcns/libboost/boost/format.hpp:38,
                 from utgcns/libpbutgcns/AlnGraphBoost.C:72:
utgcns/libboost/boost/smart_ptr/shared_ptr.hpp:529:34: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     shared_ptr & operator=( std::auto_ptr<Y> && r )
                                  ^~~~~~~~
In file included from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/locale_conv.h:41:0,
                 from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/locale:43,
                 from utgcns/libboost/boost/format.hpp:23,
                 from utgcns/libpbutgcns/AlnGraphBoost.C:72:
/cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from utgcns/libboost/boost/shared_ptr.hpp:17:0,
                 from utgcns/libboost/boost/format/alt_sstream.hpp:21,
                 from utgcns/libboost/boost/format/internals.hpp:23,
                 from utgcns/libboost/boost/format.hpp:38,
                 from utgcns/libpbutgcns/AlnGraphBoost.C:72:
utgcns/libboost/boost/smart_ptr/shared_ptr.hpp: In member function ‘boost::shared_ptr<T>& boost::shared_ptr<T>::operator=(std::auto_ptr<_Up>&&)’:
utgcns/libboost/boost/smart_ptr/shared_ptr.hpp:531:38: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
         this_type( static_cast< std::auto_ptr<Y> && >( r ) ).swap( *this );
                                      ^~~~~~~~
In file included from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/locale_conv.h:41:0,
                 from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/locale:43,
                 from utgcns/libboost/boost/format.hpp:23,
                 from utgcns/libpbutgcns/AlnGraphBoost.C:72:
/cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from utgcns/libboost/boost/smart_ptr/shared_ptr.hpp:28:0,
                 from utgcns/libboost/boost/shared_ptr.hpp:17,
                 from utgcns/libboost/boost/property_map/vector_property_map.hpp:14,
                 from utgcns/libboost/boost/property_map/property_map.hpp:600,
                 from utgcns/libboost/boost/graph/adjacency_list.hpp:36,
                 from utgcns/libpbutgcns/AlnGraphBoost.H:69,
                 from utgcns/libcns/unitigConsensus.C:77:
utgcns/libboost/boost/smart_ptr/detail/shared_count.hpp:395:33: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     explicit shared_count( std::auto_ptr<Y> & r ): pi_( new sp_counted_impl_p<Y>( r.get() ) )
                                 ^~~~~~~~
In file included from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/memory:81:0,
                 from utgcns/libboost/boost/unordered/unordered_set_fwd.hpp:14,
                 from utgcns/libboost/boost/unordered/unordered_set.hpp:17,
                 from utgcns/libboost/boost/unordered_set.hpp:17,
                 from utgcns/libboost/boost/graph/adjacency_list.hpp:21,
                 from utgcns/libpbutgcns/AlnGraphBoost.H:69,
                 from utgcns/libcns/unitigConsensus.C:77:
/cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from utgcns/libboost/boost/shared_ptr.hpp:17:0,
                 from utgcns/libboost/boost/property_map/vector_property_map.hpp:14,
                 from utgcns/libboost/boost/property_map/property_map.hpp:600,
                 from utgcns/libboost/boost/graph/adjacency_list.hpp:36,
                 from utgcns/libpbutgcns/AlnGraphBoost.H:69,
                 from utgcns/libcns/unitigConsensus.C:77:
utgcns/libboost/boost/smart_ptr/shared_ptr.hpp:242:65: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
 template< class T, class R > struct sp_enable_if_auto_ptr< std::auto_ptr< T >, R >
                                                                 ^~~~~~~~
In file included from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/memory:81:0,
                 from utgcns/libboost/boost/unordered/unordered_set_fwd.hpp:14,
                 from utgcns/libboost/boost/unordered/unordered_set.hpp:17,
                 from utgcns/libboost/boost/unordered_set.hpp:17,
                 from utgcns/libboost/boost/graph/adjacency_list.hpp:21,
                 from utgcns/libpbutgcns/AlnGraphBoost.H:69,
                 from utgcns/libcns/unitigConsensus.C:77:
/cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from utgcns/libboost/boost/shared_ptr.hpp:17:0,
                 from utgcns/libboost/boost/property_map/vector_property_map.hpp:14,
                 from utgcns/libboost/boost/property_map/property_map.hpp:600,
                 from utgcns/libboost/boost/graph/adjacency_list.hpp:36,
                 from utgcns/libpbutgcns/AlnGraphBoost.H:69,
                 from utgcns/libcns/unitigConsensus.C:77:
utgcns/libboost/boost/smart_ptr/shared_ptr.hpp:441:31: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     explicit shared_ptr( std::auto_ptr<Y> & r ): px(r.get()), pn()
                               ^~~~~~~~
In file included from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/memory:81:0,
                 from utgcns/libboost/boost/unordered/unordered_set_fwd.hpp:14,
                 from utgcns/libboost/boost/unordered/unordered_set.hpp:17,
                 from utgcns/libboost/boost/unordered_set.hpp:17,
                 from utgcns/libboost/boost/graph/adjacency_list.hpp:21,
                 from utgcns/libpbutgcns/AlnGraphBoost.H:69,
                 from utgcns/libcns/unitigConsensus.C:77:
/cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from utgcns/libboost/boost/shared_ptr.hpp:17:0,
                 from utgcns/libboost/boost/property_map/vector_property_map.hpp:14,
                 from utgcns/libboost/boost/property_map/property_map.hpp:600,
                 from utgcns/libboost/boost/graph/adjacency_list.hpp:36,
                 from utgcns/libpbutgcns/AlnGraphBoost.H:69,
                 from utgcns/libcns/unitigConsensus.C:77:
utgcns/libboost/boost/smart_ptr/shared_ptr.hpp:454:22: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     shared_ptr( std::auto_ptr<Y> && r ): px(r.get()), pn()
                      ^~~~~~~~
In file included from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/memory:81:0,
                 from utgcns/libboost/boost/unordered/unordered_set_fwd.hpp:14,
                 from utgcns/libboost/boost/unordered/unordered_set.hpp:17,
                 from utgcns/libboost/boost/unordered_set.hpp:17,
                 from utgcns/libboost/boost/graph/adjacency_list.hpp:21,
                 from utgcns/libpbutgcns/AlnGraphBoost.H:69,
                 from utgcns/libcns/unitigConsensus.C:77:
/cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from utgcns/libboost/boost/shared_ptr.hpp:17:0,
                 from utgcns/libboost/boost/property_map/vector_property_map.hpp:14,
                 from utgcns/libboost/boost/property_map/property_map.hpp:600,
                 from utgcns/libboost/boost/graph/adjacency_list.hpp:36,
                 from utgcns/libpbutgcns/AlnGraphBoost.H:69,
                 from utgcns/libcns/unitigConsensus.C:77:
utgcns/libboost/boost/smart_ptr/shared_ptr.hpp:520:34: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     shared_ptr & operator=( std::auto_ptr<Y> & r )
                                  ^~~~~~~~
In file included from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/memory:81:0,
                 from utgcns/libboost/boost/unordered/unordered_set_fwd.hpp:14,
                 from utgcns/libboost/boost/unordered/unordered_set.hpp:17,
                 from utgcns/libboost/boost/unordered_set.hpp:17,
                 from utgcns/libboost/boost/graph/adjacency_list.hpp:21,
                 from utgcns/libpbutgcns/AlnGraphBoost.H:69,
                 from utgcns/libcns/unitigConsensus.C:77:
/cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from utgcns/libboost/boost/shared_ptr.hpp:17:0,
                 from utgcns/libboost/boost/property_map/vector_property_map.hpp:14,
                 from utgcns/libboost/boost/property_map/property_map.hpp:600,
                 from utgcns/libboost/boost/graph/adjacency_list.hpp:36,
                 from utgcns/libpbutgcns/AlnGraphBoost.H:69,
                 from utgcns/libcns/unitigConsensus.C:77:
utgcns/libboost/boost/smart_ptr/shared_ptr.hpp:529:34: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     shared_ptr & operator=( std::auto_ptr<Y> && r )
                                  ^~~~~~~~
In file included from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/memory:81:0,
                 from utgcns/libboost/boost/unordered/unordered_set_fwd.hpp:14,
                 from utgcns/libboost/boost/unordered/unordered_set.hpp:17,
                 from utgcns/libboost/boost/unordered_set.hpp:17,
                 from utgcns/libboost/boost/graph/adjacency_list.hpp:21,
                 from utgcns/libpbutgcns/AlnGraphBoost.H:69,
                 from utgcns/libcns/unitigConsensus.C:77:
/cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from utgcns/libboost/boost/shared_ptr.hpp:17:0,
                 from utgcns/libboost/boost/property_map/vector_property_map.hpp:14,
                 from utgcns/libboost/boost/property_map/property_map.hpp:600,
                 from utgcns/libboost/boost/graph/adjacency_list.hpp:36,
                 from utgcns/libpbutgcns/AlnGraphBoost.H:69,
                 from utgcns/libcns/unitigConsensus.C:77:
utgcns/libboost/boost/smart_ptr/shared_ptr.hpp: In member function ‘boost::shared_ptr<T>& boost::shared_ptr<T>::operator=(std::auto_ptr<_Up>&&)’:
utgcns/libboost/boost/smart_ptr/shared_ptr.hpp:531:38: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
         this_type( static_cast< std::auto_ptr<Y> && >( r ) ).swap( *this );
                                      ^~~~~~~~
In file included from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/memory:81:0,
                 from utgcns/libboost/boost/unordered/unordered_set_fwd.hpp:14,
                 from utgcns/libboost/boost/unordered/unordered_set.hpp:17,
                 from utgcns/libboost/boost/unordered_set.hpp:17,
                 from utgcns/libboost/boost/graph/adjacency_list.hpp:21,
                 from utgcns/libpbutgcns/AlnGraphBoost.H:69,
                 from utgcns/libcns/unitigConsensus.C:77:
/cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from utgcns/libboost/boost/scoped_ptr.hpp:14:0,
                 from utgcns/libboost/boost/graph/adjacency_list.hpp:31,
                 from utgcns/libpbutgcns/AlnGraphBoost.C:74:
utgcns/libboost/boost/smart_ptr/scoped_ptr.hpp: At global scope:
utgcns/libboost/boost/smart_ptr/scoped_ptr.hpp:68:31: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     explicit scoped_ptr( std::auto_ptr<T> p ) BOOST_NOEXCEPT : px( p.release() )
                               ^~~~~~~~
In file included from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/locale_conv.h:41:0,
                 from /cm/local/apps/gcc/6.1.0/include/c++/6.1.0/locale:43,
                 from utgcns/libboost/boost/format.hpp:23,
                 from utgcns/libpbutgcns/AlnGraphBoost.C:72:
/cm/local/apps/gcc/6.1.0/include/c++/6.1.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
```

**Comment by skoren** [comment]
This looks similar to #438 though it was failing due to older GCC than you seem to have. Try removing the Linux-amd64 folder and run
```make BUILDSTACKTRACE=0```
and see if that works.

**Comment by manabanana** [comment]
@skoren 
Thank you for your speedy response!  Your suggestion worked :)!

**Comment by brianwalenz** [comment]
Yay!  You should consider upgrading your compiler, too.  GCC 6.1 is four releases out of date: https://gcc.gnu.org/gcc-6/.

**Comment by manabanana** [comment]
@brianwalenz Oh no, I'm living in the past!  Will do!
