### ISSUE TITLE
failed to add error rates to overlap store

### ISSUE THREAD

**Issue by dibyendukumar** [marbl/canu#758]
Hi,
For several days, I am stuck at unitigging/3-overlapErrorAdjustment/ stage. Our IT expert suggested to increase memory as CANU is running out of memory. I have Increased memory to all steps that seems relevant, still getting the same error. Please suggest !!!
Thanks,

CANU command
```
/ingens/apps/canu/Linux-amd64/bin/canu -assemble -p SeqTrim -d SeqRStrim gridOptionsoea="-l mem=30gb" gridOptions="-c enabled" gridOptionsGFA="-l mem
=400gb" gridOptionsovb="-l mem=150gb" gridOptionsovs="-l mem=150gb" gridOptionscorovl="-l mem=150gb" gridOptionscor="-l mem=120gb" corPartitions=1000
 minOverlapLength=1200 minReadLength=3000 ovsMemory=150g-300g genomeSize=2.3g -pacbio-corrected /***/***/***/***/canu/SeqRStrim15/SeqTrim.trimmedReads.fasta.gz'
```

I am using Canu snapshot v1.6 +120 changes (r8532 6ed280b7565194370584994956987ea4dae10a05)
unitigging/3-overlapErrorAdjustment/oea.apply.err file is empty. Upon restart, I haven't deleted 3-overlapErrorAdjustment folder.

```
CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_141' (from 'java').
-- Detected gnuplot version '4.2 patchlevel 6 ' (from 'gnuplot') and image format 'png'.
-- Detected 24 CPUs and 47 gigabytes of memory.
-- Detected PBS/Torque '' with 'pbsnodes' binary in /usr/bin/pbsnodes.
-- Detecting PBS/Torque resources.
-- 
-- Found   2 hosts with  24 cores and   47 GB memory under PBS/Torque control.
-- Found   3 hosts with  24 cores and  126 GB memory under PBS/Torque control.
-- Found   4 hosts with  64 cores and  504 GB memory under PBS/Torque control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl    126 GB   21 CPUs  (k-mer counting)
-- Grid:  cormhap   23 GB   12 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    15 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl    15 GB    8 CPUs  (overlap detection)
-- Grid:  ovb        2 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs      300 GB    1 CPU   (overlap store sorting)
-- Grid:  red       15 GB    8 CPUs  (read error detection)
-- Grid:  oea        4 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      252 GB   32 CPUs  (contig construction)
-- Grid:  cns       72 GB    8 CPUs  (consensus)
-- Grid:  gfa       23 GB   12 CPUs  (GFA alignment and processing)
--
-- Found PacBio corrected reads in 'unitigging/SeqTrim.gkpStore'.
--
-- Generating assembly 'SeqTrim' in '/***/***/***/***/canu/SeqRStrim'
--
-- Parameters:
--
--  genomeSize        2300000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN ASSEMBLY
--
----------------------------------------
-- Starting command on Thu Jan 18 12:34:55 2018 with 149640.256 GB free disk space

    cd unitigging/3-overlapErrorAdjustment
    /ingens/apps/canu-master/Linux-amd64/bin/ovStoreBuild \
      -G ../SeqTrim.gkpStore \
      -O ../SeqTrim.ovlStore \
      -evalues \
      -L ./oea.files \
    > ./oea.apply.err 2>&1
sh: line 5: 18243 Killed                  /ingens/apps/canu-master/Linux-amd64/bin/ovStoreBuild -G ../SeqTrim.gkpStore -O ../SeqTrim.ovlStore -evalue
s -L ./oea.files > ./oea.apply.err 2>&1

-- Finished on Thu Jan 18 12:35:34 2018 (39 seconds) with 149640.102 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 137.  (rc=35072)
ERROR:

ABORT:
ABORT: Canu snapshot v1.6 +120 changes (r8532 6ed280b7565194370584994956987ea4dae10a05)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to add error rates to overlap store.
ABORT:
ABORT: Disk space available:  149640.102 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (unitigging/3-overlapErrorAdjustment/oea.apply.err):
ABORT:
ABORT:
```

I have also tried latest CANU (Canu snapshot v1.6 +165 changes (r8577 c7394fc5fad5fa46264aefbcd623c7df595cce17)) that failed with following message. our IT group sugested some syntax error in the code (more on this some another time).

```
Can't "last" outside a loop block at /ingens/apps/canu-latest/Linux-amd64/bin/../lib/site_perl/canu/Gatekeeper.pm line 558.
```

**Comment by brianwalenz** [comment]
For the last error, edit src/pipelines/canu/Gatekeeper.pm and add a '#' just before 'finishStage:' at the end of the file.  I vaguely remember a different error similar to this.  I need to poke around in the code some to figure out what the other problem is - updating to the latest shouldn't fix it, as there have been no changes there recently.

**Comment by dibyendukumar** [comment]
You are right!!! ovlStore folder inside unitigging folder is 616 gb while trimming stage ovlstore is 2.4tb. Is this a bad thing for assembly? I am struggling with this genome for quite some time.
Genome has upto 85% repeat, although I used minOverlapLength=1200 and minReadLength=3000.

**Comment by skoren** [comment]
Your assembly should run if you increase the executive memory to request >50gb. The repetitive content in the genome might explain why you have so many overlaps in the store. It's not necessarily bad to have a large overlap store for the assembly, just unexpected and you may not get a very contagious assembly because of all the repeat content in your genome.

**Comment by dibyendukumar** [comment]
thanks, it worked    :(

**Comment by brianwalenz** [comment]
Reopening to remind me to find a proper fix.

**Comment by brianwalenz** [comment]
Properly fixed in 858eff83cf7a2b0c8604889072ba7567d91dfc41.  DO NOT update to this version in the middle of computing an assembly!

**Comment by lamz138138** [comment]
Hi @brianwalenz @skoren 

I have same problem except my unitigging/3-overlapErrorAdjustment/oea.apply.err is not empty, its content is:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
After reading above message, I have following question:

**I have to add "oeaMemory=50Gb" or more (default is 4gb) to solve the problem, am I right?**  

dibyendukumar mentioned decreased ovsMemory=30g-300g, on the one hand, it had spend four weeks to get all red.\*.out and oea.\*.out files, change this parameter may result in new progress, which I couldn't bear (time is expensive). On the other hand, my ovsMemory is 32G, so I don't think I have to decrease or increase it. 

By the way, following is other related information:
1) The size of unitigging/canu.ovlStore is 4.9T, which is much bigger than mentioned above.
2) Output of canu.out:
```
CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_91' (from '/path/to/tools/java/bin/java').
-- Detected gnuplot version '5.0 patchlevel 4' (from 'gnuplot') and image format 'svg'.
-- Detected 16 CPUs and 47 gigabytes of memory.
-- Detected Sun Grid Engine in '/opt/gridengine/default'.
-- User supplied Grid Engine environment '-pe myPE THREADS'.
-- User supplied Grid Engine consumable '-l mf=MEMORY'.
-- 
-- Found  22 hosts with  16 cores and   47 GB memory under Sun Grid Engine control.
-- Found   1 host  with  64 cores and  441 GB memory under Sun Grid Engine control.
-- Found   1 host  with  32 cores and  504 GB memory under Sun Grid Engine control.
-- Found   1 host  with  64 cores and  504 GB memory under Sun Grid Engine control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl    220 GB   32 CPUs  (k-mer counting)
-- Grid:  cormhap   47 GB   16 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    16 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl    16 GB    8 CPUs  (overlap detection)
-- Grid:  ovb        2 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32 GB    1 CPU   (overlap store sorting)
-- Grid:  red       16 GB    8 CPUs  (read error detection)
-- Grid:  oea        4 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      220 GB   32 CPUs  (contig construction)
-- Grid:  cns       72 GB    8 CPUs  (consensus)
-- Grid:  gfa       32 GB   16 CPUs  (GFA alignment and processing)
--
-- Found PacBio uncorrected reads in 'unitigging/canu.gkpStore'.
--
-- Generating assembly 'canu' in '/path/to/PacBio/canu/stage_1_2_3_4/canu'
--
-- Parameters:
--
--  genomeSize        3000000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN ASSEMBLY
--
----------------------------------------
-- Starting command on Sun Apr 29 05:40:21 2018 with 2258.599 GB free disk space

    cd unitigging/3-overlapErrorAdjustment
    /path/to/tools/canu_20180104/canu/Linux-amd64/bin/ovStoreBuild \
      -G ../canu.gkpStore \
      -O ../canu.ovlStore \
      -evalues \
      -L ./oea.files \
    > ./oea.apply.err 2>&1
sh: line 5: 16555 Aborted                 (core dumped) /path/to/tools/canu_20180104/canu/Linux-amd64/bin/ovStoreBuild -G ../canu.gkpStore -O ../canu.ovlStore -evalues -L ./oea.files > ./oea.apply.err 2>&1

-- Finished on Sun Apr 29 05:40:21 2018 (lickety-split) with 2258.583 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 134.  (rc=34304)
ERROR:

ABORT:
ABORT: Canu snapshot v1.6 +133 changes (r8545 f960f2ebf249ff07b991407e2b81981c46443315)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to add error rates to overlap store.
ABORT:

ABORT:
ABORT: Canu snapshot v1.6 +133 changes (r8545 f960f2ebf249ff07b991407e2b81981c46443315)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to add error rates to overlap store.
ABORT:
ABORT: Disk space available:  2258.583 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (unitigging/3-overlapErrorAdjustment/oea.apply.err):
ABORT:
ABORT:

```

**Comment by skoren** [comment]
The oeaMemory isn't related to this error and you don't need to recompute the oea files. Your store is very large so I'm guessing the oea files are large as well. You can either change ```gridOptionsExecutive="-l mf=500g"``` and re-launch or start an interactive session on your large nodes and run the failing command from inside the ```unitigging/3-overlapErrorAdjustment```:
```
    /path/to/tools/canu_20180104/canu/Linux-amd64/bin/ovStoreBuild \
      -G ../canu.gkpStore \
      -O ../canu.ovlStore \
      -evalues \
      -L ./oea.files \
    > ./oea.apply.err 2>&1
```
and it should work.

**Comment by lamz138138** [comment]
Hi, thank you for the reply!

Whether add gridOptionsExecutive="-l mf=500g" or log in one big node and run the ovStoreBuild command, it didn't work, and the error in oea.apply.err is:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
I had tried add "-M 500" when log in nodes, but it didn't work. So I check the parameter of ovStoreBuild, and found max open files. I thought it may related with max open files, but with "ulimit -a", I exclude this possibility.
```
Sizes and Limits:
  ovOverlap             2 words of 64 bits each.
  ovOverlapSortSize     256 bits
  SC_CHILD_MAX          1024 processes
  SC_OPEN_MAX           1024 files
```

```
ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 4135193
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1024
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

Is any other suggestion?

**Comment by lamz138138** [comment]
Hi @skoren 

After trying a day, I still couldn't find the solution, do you think it is because the memory is not enough?

**Comment by gringer** [comment]
How much memory does your computer have? Can you show the memory output of the `top` command?

    top -b -n 1 | grep '^KiB'

It might look something like this:

```
KiB Mem : 65929228 total,  1493340 free,  3398768 used, 61037120 buff/cache
KiB Swap: 11718699+total, 11718699+free,        0 used. 61631468 avail Mem 

```

**Comment by lamz138138** [comment]
Hi @gringer 

Thanks for the reply! There are two nodes with 500Gb and one node with 440Gb memory. 

With top command, the usage of memory is:
```
Mem:  529321736k total, 440046708k used, 89275028k free,    74872k buffers
Swap:  1023992k total,    22436k used,  1001556k free, 433124788k cached
```
and with free:
```
free -g
             total       used       free     shared    buffers     cached
Mem:           504        419         85          0          0        413
-/+ buffers/cache:          6        498
Swap:            0          0          0
```
In fact, I didn't see a lot of memory was taken after run the command of follow by logging in one node with 500Gb memory, and the programmed aborted in two minutes.
```
 /path/to/tools/canu_20180104/canu/Linux-amd64/bin/ovStoreBuild \
      -G ../canu.gkpStore \
      -O ../canu.ovlStore \
      -evalues \
      -L ./oea.files \
    > ./oea.apply.err 2>&1
```

**Comment by brianwalenz** [comment]
Here's a patch against the 1.7 release.  I could only test for compilation success; I don't have any data large enough from the version you're using to do any useful tests.  Memory usage should be trivial, about the size of any one of the files listed in oea.files.

[fix.tar.gz](https://github.com/marbl/canu/files/1959505/fix.tar.gz)

Before restarting canu, create hardlinks to the input files so they aren't accidentally deleted.
```
cd 3-overlapErrorAdjustment
mkdir save
cd save
ln ../*oea .
```
The only sanity check I can think of is to dump the overlaps before and after, and comparing the error rate in each overlap.  `ovStoreDump -G *gkpStore -O *ovlStore -d 1-10` will dump the overlaps for the first ten reads.  Error rates should generally decrease from the original to the updated version, but could slightly increase.  If there doesn't appear to be any correlation between the original and updated, something is wrong.  If there is an error, reads with high ID's will show it.  The oea.apply.err file shows which reads are changed by each input file; checking the reads of the last two input files should be sufficient.

**Comment by brianwalenz** [comment]
Just untar fix.tar.gz from within src/ and recompile.  It only changes one file.  DO NOT update from git, as there has been _a lot_ of changes to file formats and directory structures.

This command merges all those input 'oea' files into one 'evalues' file in the ovlStore.  No need to back up the store, 'undo' is simply deleting the evalues file.  I want to save the inputs because it's easy to do, and I don't remember if canu cleans up these files automagically.  And because I'm not really sure this will work (mostly sure it will).

**Comment by lamz138138** [comment]
Hi, thanks for the quickly reply!

I will try this patch (but I found there are some different between 1.6 and 1.7, so I don't know whether it works). 

For the command of ovStoreDump, do you mean "ovStoreDump -G *gkpStore -O *ovlStore >fist_file", after recompile canu 1.6, and run ovStoreBuild, run "ovStoreDump -G *gkpStore -O *ovlStore >second_file". At last, comparing these two files?

**Comment by lamz138138** [comment]
Hi @brianwalenz 

I failed at the step of re-compile, the log is:
```
WARNING:
WARNING: GCC 4.4.6 detected, disabling stack trace support.  Please upgrade to GCC 4.7 or higher.
WARNING:
Building for 'Linux' '2.6.32-220.el6.x86_64' as 'amd64' into '/data7/lcy/zhongxm/tools/canu_20180104/canu/Linux-amd64/{bin,obj}'
CC  cc 4.4.6
CXX g++ 5.4.0
Building snapshot v1.6 +133 changes (r8545 f960f2ebf249ff07b991407e2b81981c46443315) (ahead of github)

g++ -o /data7/lcy/zhongxm/tools/canu_20180104/canu/Linux-amd64/obj/lib/libcanu.a/stores/ovStore.o -c -MD -D_GLIBCXX_PARALLEL -pthread -fopenmp -fPIC -Wall -Wextra -Wno-write-strings -Wno-unused -Wno-char-subscripts -Wno-sign-compare -Wformat -g3 -O4 -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer -DNOBACKTRACE -I/data7/lcy/zhongxm/tools/canu_20180104/canu/src -IAS_UTL -Istores -Istores/libsnappy -Ialignment -Iutgcns/libNDalign -Iutgcns/libcns -Iutgcns/libpbutgcns -Iutgcns/libNDFalcon -Iutgcns/libboost -Imeryl/libleaff -IoverlapInCore -IoverlapInCore/libedlib -IoverlapInCore/liboverlap -Ifalcon_sense/libfalcon stores/ovStore.C
stores/ovStore.C: In destructor ‘ovStore::~ovStore()’:
stores/ovStore.C:148:29: error: ‘AS_UTL_closeFile’ was not declared in this scope
   AS_UTL_closeFile(_offtFile);
                             ^
stores/ovStore.C: In member function ‘void ovStore::addEvalues(std::vector<char*>&)’:
stores/ovStore.C:602:23: error: ‘AS_UTL_closeFile’ was not declared in this scope
     AS_UTL_closeFile(E);
                       ^
stores/ovStore.C:640:34: error: ‘AS_UTL_closeFile’ was not declared in this scope
   AS_UTL_closeFile(EO, evalueTemp);
                                  ^
stores/ovStore.C:646:39: error: ‘AS_UTL_rename’ was not declared in this scope
   AS_UTL_rename(evalueTemp, evalueName);
                                       ^
make: *** [/data7/lcy/zhongxm/tools/canu_20180104/canu/Linux-amd64/obj/lib/libcanu.a/stores/ovStore.o] Error 1
```

**Comment by brianwalenz** [comment]
And that's what I get for testing against v1.7.  :-(  Here's one that compiles with v1.6.  It's a bit unsafe in that it could crash when expected files don't exist, so don't release it to production.

[fix2.tar.gz](https://github.com/marbl/canu/files/1960013/fix2.tar.gz)

**Comment by lamz138138** [comment]
Hi

There still a problem, what should be changed?
```
WARNING:
WARNING: GCC 4.4.6 detected, disabling stack trace support.  Please upgrade to GCC 4.7 or higher.
WARNING:
Building for 'Linux' '2.6.32-220.el6.x86_64' as 'amd64' into '/path/to/tools/canu_20180104/canu/Linux-amd64/{bin,obj}'
CC  cc 4.4.6
CXX g++ 5.4.0
make: Warning: File `stores/ovStore.C' has modification time 2.4e+04 s in the future
Building snapshot v1.6 +133 changes (r8545 f960f2ebf249ff07b991407e2b81981c46443315) (ahead of github)

g++ -o /path/to/tools/canu_20180104/canu/Linux-amd64/obj/lib/libcanu.a/stores/ovStore.o -c -MD -D_GLIBCXX_PARALLEL -pthread -fopenmp -fPIC -Wall -Wextra -Wno-write-strings -Wno-unused -Wno-char-subscripts -Wno-sign-compare -Wformat -g3 -O4 -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer -DNOBACKTRACE -I/path/to/tools/canu_20180104/canu/src -IAS_UTL -Istores -Istores/libsnappy -Ialignment -Iutgcns/libNDalign -Iutgcns/libcns -Iutgcns/libpbutgcns -Iutgcns/libNDFalcon -Iutgcns/libboost -Imeryl/libleaff -IoverlapInCore -IoverlapInCore/libedlib -IoverlapInCore/liboverlap -Ifalcon_sense/libfalcon stores/ovStore.C
stores/ovStore.C:496:64: error: no ‘uint32* ovStore::numOverlapsPerFrag(uint32&, uint32&)’ member function declared in class ‘ovStore’
 ovStore::numOverlapsPerFrag(uint32 &firstFrag, uint32 &lastFrag) {
                                                                ^
make: *** [/path/to/tools/canu_20180104/canu/Linux-amd64/obj/lib/libcanu.a/stores/ovStore.o] Error 1
```

Besides, For the command of ovStoreDump, do you mean "ovStoreDump -G *gkpStore -O *ovlStore >fist_file", after recompile canu 1.6, and run ovStoreBuild, run "ovStoreDump -G *gkpStore -O *ovlStore >second_file". At last, comparing these two files?

**Comment by brianwalenz** [comment]
Argh, halfway between v1.6 and v1.7!  Third try.

[fix3.tar.gz](https://github.com/marbl/canu/files/1960146/fix3.tar.gz)

For ovStoreDump, yes, that'd work.  Don't forget the '-d 1-10' option.  Without '-d', it'll just print the usage statement, and without the read range, it'll dump all overlaps.

**Comment by lamz138138** [comment]
Hi brianwalenz!

I had finished the step of ovStoreDump. Then, I move evalues file out of *ovlStore, and run "ovStoreDump -G *gkpStore -O *ovlStore -d 1-10>fist_file" using the old ovStoreDump (I had backup all old canu directory, I think there is no different between old and re-compile of ovStoreDump).  Move evalues file back to *ovlStore, and run "ovStoreDump -G *gkpStore -O *ovlStore -d 1-10>fist_file" using re-compile canu. Since head and tail of first is less than second, I think I can continue assembly, am I right?

Following is head and tail of first and second files:
```
head first 
         2     227711  N    4209       0   4162    9099  13242  0.030900
         2     893774  I    4805     317   5068    4701      0  0.038500
         2    1238877  I    5485    4108   9543    6852   1440  0.027000
         2    1441802  I    7058    2565   9543   12352   5349  0.024600
         2    1863349  I    3435       0   3362    3376      0  0.044900
         2    2105664  N    1543       0   1529    7636   9149  0.035000
         2    2997035  I    5413    4178   9543    5777    400  0.017300
         2    3019814  I    2523    7041   9543    9343   6839  0.017600
         2    3223849  I    3283    6106   9356    3258      0  0.020000
         2    4119676  N    9645       0   9543    2910  12492  0.019200
```
```
head second 
         2     227711  N    4209       0   4162    9099  13242  0.027300
         2     893774  I    4805     317   5068    4701      0  0.030600
         2    1238877  I    5485    4108   9543    6852   1440  0.023500
         2    1441802  I    7058    2565   9543   12352   5349  0.019800
         2    1863349  I    3435       0   3362    3376      0  0.027700
         2    2105664  N    1543       0   1529    7636   9149  0.030400
         2    2997035  I    5413    4178   9543    5777    400  0.014600
         2    3019814  I    2523    7041   9543    9343   6839  0.014400
         2    3223849  I    3283    6106   9356    3258      0  0.015400
         2    4119676  N    9645       0   9543    2910  12492  0.015100
```

```
tail first 
        10   14037988  N   11846       0  11689       0  11662  0.033400
        10   14214452  I     783   10916  11689   15373  14604  0.039000
        10   14214453  N     807   10890  11689       0    799  0.025000
        10   14485383  N   11766       0  11689    1591  13315  0.011500
        10   15383828  I   11853       0  11689   20845   9064  0.024000
        10   16625099  I    1558    7990   9538    1531      0  0.029400
        10   16728042  N    1481       0   1473    6913   8380  0.019800
        10   18023796  N    7850    3895  11689       0   7825  0.012400
        10   18023797  I    3935    7778  11689    9031   5121  0.014600
        10   18130556  I    1394       0   1379    1374      0  0.032800
```
```
tail second 
        10   14037988  N   11846       0  11689       0  11662  0.024300
        10   14214452  I     783   10916  11689   15373  14604  0.031300
        10   14214453  N     807   10890  11689       0    799  0.021400
        10   14485383  N   11766       0  11689    1591  13315  0.010000
        10   15383828  I   11853       0  11689   20845   9064  0.021100
        10   16625099  I    1558    7990   9538    1531      0  0.022300
        10   16728042  N    1481       0   1473    6913   8380  0.017700
        10   18023796  N    7850    3895  11689       0   7825  0.009900
        10   18023797  I    3935    7778  11689    9031   5121  0.012800
        10   18130556  I    1394       0   1379    1374      0  0.025600
```

**Comment by brianwalenz** [comment]
The changes only affected ovStoreBuild.

Check the same for the last read - this will ensure that the evalues file isn't truncated.  This would get tested eventually, but better to do it quickly now.  If reasonable values are reported, you should be good to proceed.  I think it'll just crash if the file is truncated.

Out of curiosity, how big is this evalues file?

**Comment by lamz138138** [comment]
Hi, I checked the last read, the ID is same and it decrease in update version. The evalues file is 500G, and I have following questions: 
1) Is it much bigger than others?
2) If the answer of above question is true, is it means my genome is high repeat, and the continuity of my assembly would be worse (in fact, with falcon, N50 is 1.2Mb)?
3) Why I got above error ("std::bad_alloc"), is it caused by too much overlap?

**Comment by lamz138138** [comment]
Hi @brianwalenz @skoren 

I had finished the process of assembly. However, the assembly is awful, with N50 is 600Kb, and the longest contig is 6Mb. According to *.report, I think I had got enough reads to perform assembly:
```
[CORRECTION/READS]
--
-- In gatekeeper store './canu.gkpStore':
--   Found 18670799 reads.
--   Found 183785190540 bases (61.26 times coverage).

....

[TRIMMING/READS]
--
-- In gatekeeper store './canu.gkpStore':
--   Found 10441560 reads.
--   Found 90842445386 bases (30.28 times coverage).
```

Is the genome is too repeat to assembly? Since the *.ovlStore is three times bigger than human (I had saw the ovlStore of human is ~1.5T, while mine is ~4.9T. Besides, the genome of mine is a primate, and you can take it as human). But, considering the alignment of these reads to reference, I don't think it is too repeat. So I have follow questions:
1) Is any other parameter should I changed (I use default parameter at the moment)?
2) Is it worth to sequencing another 30X data? In my opinion, since it is so awful with above 60X data, I don't think add 30X new data would improve it greatly.
3) Could you answer previously questions?

Thanks in advance!

**Comment by skoren** [comment]
Calling a 600kb n50 awful is a stretch. You've got quite a repetitive genome based on the overlaps so there's limitations to what can be done with long reads. Also, n50 is a poor measure since it ignores correctness/assembly size differences/etc. At the very least you should use NG50 with a fixed genome size when comparing assemblies. If your genome heterozygosity is high I expect the Canu assembly would be larger than the falcon assembly because it split out the haplotypes and did not try to segregate them into primary/alt like falcon does.

To answer your questions:
1/2. There isn't enough information to answer that question. It depends on the current read length distribution/genome repeat size/genome heterozygosity/sequencing type (Sequel? RSII?). As a start your full *.report file would help plus the histogram file from either ```trimming/0-*``` or ```unitigging/0-*```. The answer as to parameters will depend on the same information, you need to understand the genome well to adjust parameters.

3. Yes, 500g is much larger than other evalues files we've seen, this implies there are a lot of overlaps and likely a lot of repeats in the genome. You got an error because you hit a bug in an older version of Canu which has since been fixed.

**Comment by lamz138138** [comment]
It is a specie closely related to human (25~30 Mya), so I don't think it would  be so repeated, do you think it is the problem of experiment of sequencing?

**Comment by skoren** [comment]
Would need the information I listed above to answer that, going just by amount of overlap it has some repetitive sequences that human does not or it wouldn't have such a large overlap store.

**Comment by lamz138138** [comment]
Thanks for the reply, I would draw the distribution of read length base on correctedReads.fasta.gz and trimmedReads.fasta.gz (I had draw the distribution of falcon correct reads, and it seemed normal). 

Beisdes, for the 60X data, about 40X is RSII data and 20X is Sequel data, I had thought they were identical as the error rate is similar, do you think this is a problem?

**Comment by skoren** [comment]
You can put the histogram from Canu into a model that will estimate the genome size/heterozygosity/repeat content like GenomeScope to get more information on your genome.

The Sequel data has to date been higher error and shorter than the RSII so it may help to increase your error rate but given the already large unitig store, we'd need to adjust other parameters to do that to avoid further increases in size.
