### ISSUE TITLE
meryl failed

### ISSUE THREAD

**Issue by Luis3A** [marbl/canu#226]
Hello,

I'm trying to use canu. I installed by git clone git://github.com/marbl/canu + cd canu/src + make -j 1

It worked (since neither binaries or source worked then I tried):
Success!
canu installed in /Users/luis/Desktop/canu/Darwin-amd64/bin/canu

I tested canu with the _E. coli_ data provided. And I got a error message:
```
-- meryl failed.
--
-- Meryl attempt 2 begins.
----------------------------------------
-- Starting concurrent execution on Thu Aug 11 09:23:28 2016 with 5067.483 GB free disk space (1 processes; 4 concurrently)

    /Users/luis/Desktop/JabbaAll/ecoli-auto/correction/0-mercounts/meryl.sh 1 > /Users/luis/Desktop/JabbaAll/ecoli-auto/correction/0-mercounts/meryl.000001.out 2>&1

-- Finished on Thu Aug 11 09:23:29 2016 (1 second) with 5067.483 GB free disk space
----------------------------------------
--
-- meryl failed.
--
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'failed to generate mer counts.  Made 2 attempts, jobs still failed'.
```

So I tried to look for answers in here since some users posted things in that sense but I dont seem to have a problem in privileges in the meryl.sh ... I don't know what else to do.

This is the meryl.sh :
```
#!/bin/sh

if [ -e /Users/luis/Desktop/JabbaAll/ecoli-auto/correction/ecoli.tigStore/seqDB.v001.tig ] ; then
  exit 0
fi

syst=`uname -s`
arch=`uname -m`
name=`uname -n`

if [ "$arch" = "x86_64" ] ; then
  arch="amd64"
fi
if [ "$arch" = "Power Macintosh" ] ; then
  arch="ppc"
fi

bin="/Users/luis/Desktop/canu/$syst-$arch/bin"

if [ ! -d "$bin" ] ; then
  bin="/Users/luis/Desktop/canu"
fi


#  Purge any previous intermediate result.  Possibly not needed, but safer.

rm -f /Users/luis/Desktop/JabbaAll/ecoli-auto/correction/0-mercounts/ecoli.ms16.WORKING*

$bin/meryl \
  -B -C -L 2 -v -m 16 -threads 4 -memory 6553 \
  -s /Users/luis/Desktop/JabbaAll/ecoli-auto/correction/ecoli.gkpStore \
  -o /Users/luis/Desktop/JabbaAll/ecoli-auto/correction/0-mercounts/ecoli.ms16.WORKING \
&& \
mv /Users/luis/Desktop/JabbaAll/ecoli-auto/correction/0-mercounts/ecoli.ms16.WORKING.mcdat /Users/luis/Desktop/JabbaAll/ecoli-auto/correction/0-mercounts/ecoli.ms16.FINISHED.mcdat \
&& \
mv /Users/luis/Desktop/JabbaAll/ecoli-auto/correction/0-mercounts/ecoli.ms16.WORKING.mcidx /Users/luis/Desktop/JabbaAll/ecoli-auto/correction/0-mercounts/ecoli.ms16.FINISHED.mcidx

exit 0
```

I hope that's enough for you to help me. If not, please tell me so I could give you more information.

Thank you very much,

Luis

**Comment by brianwalenz** [comment]
What is in `/Users/luis/Desktop/JabbaAll/ecoli-auto/correction/0-mercounts/meryl.000001.out`?

Can you run `/Users/luis/Desktop/canu/Darwin-amd64/bin/meryl` from the command line?  I suspect it is going to be complaining about not finding some library.

What compiler are you using (gcc --version)?  Is it from MacPorts or homebrew?  What version of OSX are you using?

What problem did you have with the 1.3 binary download?

Sorry for the many questions.

**Comment by Luis3A** [comment]
Thank you for your answer.

1) What is in /Users/luis/Desktop/JabbaAll/ecoli-auto/correction/0-mercounts/meryl.000001.out?
Here is the meryl.000001.out file:
[meryl.000001.out.txt](https://github.com/marbl/canu/files/412925/meryl.000001.out.txt)

2) Can you run /Users/luis/Desktop/canu/Darwin-amd64/bin/meryl from the command line?
Yes I can, it does not complain. It just gives me the usage:
usage: /Users/luis/Desktop/canu/Darwin-amd64/bin/meryl [personality] [global options] [options]
---> What files should I pass it ?

3)What compiler are you using (gcc --version)?
I used gcc:
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

4)Is it from MacPorts or homebrew?
It is from Xcode, I installed the homebrew version but it ignores it and just use Xcode.

5) What version of OSX are you using?
My OSX is 10.11.6 (El Capitan).

6) What problem did you have with the 1.3 binary download?
falcon_sense/falcon_sense.C:33:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^
1 error generated.
make: *** [/Users/luis/Desktop/canu-1.3/Darwin-amd64/obj/falcon_sense/falcon_sense/falcon_sense.o] Error 1

Thank you again,

Luis

**Comment by brianwalenz** [comment]
If you set environment variables CC and CXX to point to the homebrew gcc and g++ (which might be installed as something similar to gcc-4.8), the canu build will use those instead of the default compiler.

For question 6, you're still compiling from source, with clang.  I meant the pre-compiled 1.3 release available on https://github.com/marbl/canu/releases.

Before we debug further (below) recompile with homebrew gcc or install the 1.3 binaries.

We do a fair amount of development on 10.11.5 with gcc, but rarely (if ever) test with clang.

**Comment by Luis3A** [comment]
Hello again,

Ok sorry for question 6, I misread... when I use the binairies I got the same error that opened this issue i.e. 
[Merylerror.txt](https://github.com/marbl/canu/files/421992/Merylerror.txt)

I can't seem to set CC and CXX variables
when I do:
set CC=/usr/local/Cellar/gcc48/4.8.5/gcc
set CXX=/usr/local/Cellar/gcc48/4.8.5/g++
and install canu from src, it uses clang.

Thank you again. And sorry for my questions.

**Comment by brianwalenz** [comment]
In bash shell, try

export CC=/usr/local/Cellar/gcc48/4.8.5/gcc
export CXX=/usr/local/Cellar/gcc48/4.8.5/g++

It might work to do

make CC=/usr/local/Cellar/gcc48/4.8.5/gcc CXX=/usr/local/Cellar/gcc48/4.8.5/g++

And if those fail, edit src/Makefile and change the definitions at line 406 to point to your gcc48.

```
ifeq (${OSTYPE}, Darwin)
  CLANG = $(shell echo `${CXX} --version 2>&1 | grep -c clang`)

  CC       ?= gcc    <---- CHANGE THESE
  CXX      ?= g++  <----
  ifeq ($(CLANG), 0)
     CXXFLAGS := -pthread -fopenmp -fPIC -m64 -Wall -Wextra -Wno-write-strings -Wno-unused -Wno-char-subscripts -Wno-sign-compare -Wformat
     LDFLAGS  := -pthread -fopenmp -lm
  else
```

(I don't know homebrew, but why are these in 'Cellar'?  That sounds like you might have uninstalled or deactivated it.)

**Comment by Luis3A** [comment]
Ok so here´s what I did:
in bash shell:
which gcc-4.8 it returns : /usr/local/bin/gcc-4.8 
which g++-4.8 it returns : /usr/local/bin/g++-4.8 

so I did:
export CC=/usr/local/bin/gcc-4.8
export CC=/usr/local/bin/g++-4.8

then I opened the makefile and changed lines 406 and 407 so they are now:
  CC       ?= /usr/local/bin/gcc-4.8
  CXX      ?= /usr/local/bin/g++-4.8

and then I did:
make -j8

Success !

and now everything works !!!
Thank you very much.

**Comment by yukicyk** [comment]
This solved my problem for compiling canu 1.3 on my Mac as well, thanks. I'm using home-brewed gcc 6.2.0 .

And I find the followed problem before when I tried with the 1.3 binary download

```
dyld: lazy symbol binding failed: Symbol not found: _Perl_xs_handshake
  Referenced from: /Users/OB/Desktop/Yuki/Tools/canu-1.3-Darwin/Darwin-amd64/bin/lib/canu/lib/perl5/darwin-thread-multi-2level/auto/Filesys/Df/Df.bundle
  Expected in: flat namespace

dyld: Symbol not found: _Perl_xs_handshake
  Referenced from: /Users/OB/Desktop/Yuki/Tools/canu-1.3-Darwin/Darwin-amd64/bin/lib/canu/lib/perl5/darwin-thread-multi-2level/auto/Filesys/Df/Df.bundle
  Expected in: flat namespace

Trace/BPT trap: 5
```

**Comment by brianwalenz** [comment]
In summary:

Use either (note second line sets CXX, not CC as Luis3A did above):
```
export CC=/usr/local/bin/gcc-4.8
export CXX=/usr/local/bin/g++-4.8
```
Or, edit Makefile lines 406 and 407 to be:
```
CC ?= /usr/local/bin/gcc-4.8
CXX ?= /usr/local/bin/g++-4.8
```
(doing both is OK too, but either one should work)

The perl issue will not happen anymore.  We have removed the Filesys-Df dependency.
