### ISSUE TITLE
bogus build failed

### ISSUE THREAD

**Issue by tolot27** [marbl/canu#411]
Build on Ubuntu 16.04 of 2535e0d01 failed for bogus with error
```
Building for 'Linux' '4.4.0-64-generic' as 'amd64' into '/mnt/soft/canu.git/Linux-amd64/{bin,obj}'
Building v1.4 (+141 commits) r8136 15318d8b9935f36a9cffa6026f1a6102535e0d01 (sync'd with guthub)

g++ -o /mnt/soft/canu.git/Linux-amd64/bin/bogus -D_GLIBCXX_PARALLEL -pthread -fopenmp -lm -L/mnt/soft/canu.git/Linux-amd64/bin /mnt/soft/canu.git/Linux-amd64/obj/bogus/bogus/bogus.o /mnt/soft/canu.git/Linux-amd64/obj/bogus/bogus/bogusUtil.o -lcanu
/mnt/soft/canu.git/Linux-amd64/obj/bogus/bogus/bogus.o: In function `main':
/BioInformatics/soft/canu.git/src/bogus/bogus.C:559: undefined reference to `loadReferenceSequence(char*, std::vector<referenceSequence, std::allocator<referenceSequence> >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned int> > >&)'
/BioInformatics/soft/canu.git/src/bogus/bogus.C:565: undefined reference to `loadNucmer(char*, std::vector<genomeAlignment, std::allocator<genomeAlignment> >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::vector<referenceSequence, std::allocator<referenceSequence> >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned int> > >&, double)'
...
/mnt/soft/canu.git/Linux-amd64/obj/bogus/bogus/bogus.o: In function `main':
/BioInformatics/soft/canu.git/src/bogus/bogus.C:568: undefined reference to `loadSnapper(char*, std::vector<genomeAlignment, std::allocator<genomeAlignment> >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::vector<referenceSequence, std::allocator<referenceSequence> >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned int> > >&, double)'
...
collect2: error: ld returned 1 exit status
Makefile:567: recipe for target '/mnt/soft/canu.git/Linux-amd64/bin/bogus' failed
make: *** [/mnt/soft/canu.git/Linux-amd64/bin/bogus] Error 1
```

I do not see any obvious error in the make files. Both `bogus.o` and `bogusUtil.o` were built. Other binaries were built as well.

**Comment by brianwalenz** [comment]
I'm suspecting a race condition in the build - two processes tried to add to the library at the same time, and bogusUtil lost.  Try removing the Linux-amd64 directory and rebuilding.  This will remove all traces of the previous compile.

If that doesn't work, remove the 'bogus/bogus.mk' from src/main.mk.  This will skip the 'bogus' compilation (bogus isn't used in canu).  Note that you can't just comment the line out; it needs to be removed from that list.

**Comment by tolot27** [comment]
Removing Linux-amd64 and rebuilding with just 10 threads (instead of 30 threads previously used) worked. Thanks!
