### ISSUE TITLE
unable to install canu

### ISSUE THREAD

**Issue by amit4mchiba** [marbl/canu#438]
Hi,

While installing canu is very very easy and i have done it before, i donot know why i am not able to do it in another computer cluster that i recently got access to. I am not sure what information i should ask from system adminstrator to resolve this issue. Please help. Here is the full message while installing canu from git-hub-
```
Building for 'Linux' '2.6.32-431.5.1.el6.x86_64' as 'amd64' into '/gwfefs/home/genome99/canu_git/canu/Linux-amd64/{bin,obj}'
CC cc CXX g++
Building snapshot v1.4 (+180 changes) r8175 63e2ea3683e433e880da51a8911793b88217a519 (sync'd with guthub)

cc -o /gwfefs/home/genome99/canu_git/canu/Linux-amd64/obj/libcanu.a/AS_UTL/libbacktrace/atomic.o -c -MD -I/gwfefs/home/genome99/canu_git/canu/src -IAS_UTL -Istores -Istores/libsnappy -Ialignment -Iutgcns/libNDalign -Iutgcns/libcns -Iutgcns/libpbutgcns -Iutgcns/libNDFalcon -Iutgcns/libboost -Imeryl/libleaff -IoverlapInCore -IoverlapInCore/libedlib -IoverlapInCore/liboverlap -Ifalcon_sense/libfalcon AS_UTL/libbacktrace/atomic.c
cc -o /gwfefs/home/genome99/canu_git/canu/Linux-amd64/obj/libcanu.a/AS_UTL/libbacktrace/backtrace.o -c -MD -I/gwfefs/home/genome99/canu_git/canu/src -IAS_UTL -Istores -Istores/libsnappy -Ialignment -Iutgcns/libNDalign -Iutgcns/libcns -Iutgcns/libpbutgcns -Iutgcns/libNDFalcon -Iutgcns/libboost -Imeryl/libleaff -IoverlapInCore -IoverlapInCore/libedlib -IoverlapInCore/liboverlap -Ifalcon_sense/libfalcon AS_UTL/libbacktrace/backtrace.c
cc -o /gwfefs/home/genome99/canu_git/canu/Linux-amd64/obj/libcanu.a/AS_UTL/libbacktrace/dwarf.o -c -MD -I/gwfefs/home/genome99/canu_git/canu/src -IAS_UTL -Istores -Istores/libsnappy -Ialignment -Iutgcns/libNDalign -Iutgcns/libcns -Iutgcns/libpbutgcns -Iutgcns/libNDFalcon -Iutgcns/libboost -Imeryl/libleaff -IoverlapInCore -IoverlapInCore/libedlib -IoverlapInCore/liboverlap -Ifalcon_sense/libfalcon AS_UTL/libbacktrace/dwarf.c
cc -o /gwfefs/home/genome99/canu_git/canu/Linux-amd64/obj/libcanu.a/AS_UTL/libbacktrace/elf.o -c -MD -I/gwfefs/home/genome99/canu_git/canu/src -IAS_UTL -Istores -Istores/libsnappy -Ialignment -Iutgcns/libNDalign -Iutgcns/libcns -Iutgcns/libpbutgcns -Iutgcns/libNDFalcon -Iutgcns/libboost -Imeryl/libleaff -IoverlapInCore -IoverlapInCore/libedlib -IoverlapInCore/liboverlap -Ifalcon_sense/libfalcon AS_UTL/libbacktrace/elf.c
cc -o /gwfefs/home/genome99/canu_git/canu/Linux-amd64/obj/libcanu.a/AS_UTL/libbacktrace/fileline.o -c -MD -I/gwfefs/home/genome99/canu_git/canu/src -IAS_UTL -Istores -Istores/libsnappy -Ialignment -Iutgcns/libNDalign -Iutgcns/libcns -Iutgcns/libpbutgcns -Iutgcns/libNDFalcon -Iutgcns/libboost -Imeryl/libleaff -IoverlapInCore -IoverlapInCore/libedlib -IoverlapInCore/liboverlap -Ifalcon_sense/libfalcon AS_UTL/libbacktrace/fileline.c
cc -o /gwfefs/home/genome99/canu_git/canu/Linux-amd64/obj/libcanu.a/AS_UTL/libbacktrace/mmap.o -c -MD -I/gwfefs/home/genome99/canu_git/canu/src -IAS_UTL -Istores -Istores/libsnappy -Ialignment -Iutgcns/libNDalign -Iutgcns/libcns -Iutgcns/libpbutgcns -Iutgcns/libNDFalcon -Iutgcns/libboost -Imeryl/libleaff -IoverlapInCore -IoverlapInCore/libedlib -IoverlapInCore/liboverlap -Ifalcon_sense/libfalcon AS_UTL/libbacktrace/mmap.c
AS_UTL/libbacktrace/dwarf.c: In function ‘dwarf_lookup_pc’:
AS_UTL/libbacktrace/dwarf.c:2779: error: ‘__ATOMIC_ACQUIRE’ undeclared (first use in this function)
AS_UTL/libbacktrace/dwarf.c:2779: error: (Each undeclared identifier is reported only once
AS_UTL/libbacktrace/dwarf.c:2779: error: for each function it appears in.)
AS_UTL/libbacktrace/dwarf.c:2839: error: ‘__ATOMIC_RELEASE’ undeclared (first use in this function)
AS_UTL/libbacktrace/dwarf.c: In function ‘dwarf_fileline’:
AS_UTL/libbacktrace/dwarf.c:2974: error: ‘__ATOMIC_ACQUIRE’ undeclared (first use in this function)
AS_UTL/libbacktrace/dwarf.c: In function ‘backtrace_dwarf_add’:
AS_UTL/libbacktrace/dwarf.c:3107: error: ‘__ATOMIC_ACQUIRE’ undeclared (first use in this function)
make: *** [/gwfefs/home/genome99/canu_git/canu/Linux-amd64/obj/libcanu.a/AS_UTL/libbacktrace/dwarf.o] Error 1
make: *** Waiting for unfinished jobs....
AS_UTL/libbacktrace/fileline.c: In function ‘fileline_initialize’:
AS_UTL/libbacktrace/fileline.c:64: error: ‘__ATOMIC_ACQUIRE’ undeclared (first use in this function)
AS_UTL/libbacktrace/fileline.c:64: error: (Each undeclared identifier is reported only once
AS_UTL/libbacktrace/fileline.c:64: error: for each function it appears in.)
AS_UTL/libbacktrace/fileline.c:146: error: ‘__ATOMIC_RELEASE’ undeclared (first use in this function)
make: *** [/gwfefs/home/genome99/canu_git/canu/Linux-amd64/obj/libcanu.a/AS_UTL/libbacktrace/fileline.o] Error 1
AS_UTL/libbacktrace/elf.c: In function ‘elf_add_syminfo_data’:
AS_UTL/libbacktrace/elf.c:450: error: ‘__ATOMIC_ACQUIRE’ undeclared (first use in this function)
AS_UTL/libbacktrace/elf.c:450: error: (Each undeclared identifier is reported only once
AS_UTL/libbacktrace/elf.c:450: error: for each function it appears in.)
AS_UTL/libbacktrace/elf.c: In function ‘elf_syminfo’:
AS_UTL/libbacktrace/elf.c:495: error: ‘__ATOMIC_ACQUIRE’ undeclared (first use in this function)
AS_UTL/libbacktrace/elf.c: In function ‘backtrace_initialize’:
AS_UTL/libbacktrace/elf.c:960: error: ‘__ATOMIC_RELEASE’ undeclared (first use in this function)
AS_UTL/libbacktrace/elf.c:975: error: ‘__ATOMIC_ACQUIRE’ undeclared (first use in this function)
make: *** [/gwfefs/home/genome99/canu_git/canu/Linux-amd64/obj/libcanu.a/AS_UTL/libbacktrace/elf.o] Error 1
utgcns/libcns/unitigConsensus.C: In function ‘void _ZN15unitigConsensus13generatePBDAGEcP5tgTigPNSt9__cxx19983mapIjP6gkReadSt4lessIjESaISt4pairIKjS5_EEEEPNS3_IjP10gkReadDataS7_SaIS8_IS9_SF_EEEE.omp_fn.0(void*)’:
utgcns/libcns/unitigConsensus.C:367: warning: ‘align.EdlibAlignResult::alignmentLength’ may be used uninitialized in this function
utgcns/libcns/unitigConsensus.C:367: note: ‘align.EdlibAlignResult::alignmentLength’ was declared here
```

**Comment by brianwalenz** [comment]
What version of 'cc' and 'g++' are being used?

Does setting CC=gcc resolve the problem?

**Comment by amit4mchiba** [comment]
Thank you so much for such a quick reply.

I am really sorry, but i am a beginner. I donot know how to set cc=gcc. Please guide me.

**Comment by amit4mchiba** [comment]
I tried this-
[genome99@greatwave1 src]$ make -j8 CC=gcc

I am not sure if this is what you meant, but seems not helping if i have done it correctly
Building for 'Linux' '2.6.32-431.5.1.el6.x86_64' as 'amd64' into '/gwfefs/home/genome99/canu_git/canu/Linux-amd64/{bin,obj}'
CC gcc CXX g++
gcc -o /gwfefs/home/genome99/canu_git/canu/Linux-amd64/obj/libcanu.a/AS_UTL/libbacktrace/dwarf.o -c -MD -I/gwfefs/home/genome99/canu_git/canu/src -IAS_UTL -Istores -Istores/libsnappy -Ialignment -Iutgcns/libNDalign -Iutgcns/libcns -Iutgcns/libpbutgcns -Iutgcns/libNDFalcon -Iutgcns/libboost -Imeryl/libleaff -IoverlapInCore -IoverlapInCore/libedlib -IoverlapInCore/liboverlap -Ifalcon_sense/libfalcon AS_UTL/libbacktrace/dwarf.c
gcc -o /gwfefs/home/genome99/canu_git/canu/Linux-amd64/obj/libcanu.a/AS_UTL/libbacktrace/elf.o -c -MD -I/gwfefs/home/genome99/canu_git/canu/src -IAS_UTL -Istores -Istores/libsnappy -Ialignment -Iutgcns/libNDalign -Iutgcns/libcns -Iutgcns/libpbutgcns -Iutgcns/libNDFalcon -Iutgcns/libboost -Imeryl/libleaff -IoverlapInCore -IoverlapInCore/libedlib -IoverlapInCore/liboverlap -Ifalcon_sense/libfalcon AS_UTL/libbacktrace/elf.c
gcc -o /gwfefs/home/genome99/canu_git/canu/Linux-amd64/obj/libcanu.a/AS_UTL/libbacktrace/fileline.o -c -MD -I/gwfefs/home/genome99/canu_git/canu/src -IAS_UTL -Istores -Istores/libsnappy -Ialignment -Iutgcns/libNDalign -Iutgcns/libcns -Iutgcns/libpbutgcns -Iutgcns/libNDFalcon -Iutgcns/libboost -Imeryl/libleaff -IoverlapInCore -IoverlapInCore/libedlib -IoverlapInCore/liboverlap -Ifalcon_sense/libfalcon AS_UTL/libbacktrace/fileline.c
gcc -o /gwfefs/home/genome99/canu_git/canu/Linux-amd64/obj/libcanu.a/AS_UTL/libbacktrace/mmapio.o -c -MD -I/gwfefs/home/genome99/canu_git/canu/src -IAS_UTL -Istores -Istores/libsnappy -Ialignment -Iutgcns/libNDalign -Iutgcns/libcns -Iutgcns/libpbutgcns -Iutgcns/libNDFalcon -Iutgcns/libboost -Imeryl/libleaff -IoverlapInCore -IoverlapInCore/libedlib -IoverlapInCore/liboverlap -Ifalcon_sense/libfalcon AS_UTL/libbacktrace/mmapio.c
gcc -o /gwfefs/home/genome99/canu_git/canu/Linux-amd64/obj/libcanu.a/AS_UTL/libbacktrace/posix.o -c -MD -I/gwfefs/home/genome99/canu_git/canu/src -IAS_UTL -Istores -Istores/libsnappy -Ialignment -Iutgcns/libNDalign -Iutgcns/libcns -Iutgcns/libpbutgcns -Iutgcns/libNDFalcon -Iutgcns/libboost -Imeryl/libleaff -IoverlapInCore -IoverlapInCore/libedlib -IoverlapInCore/liboverlap -Ifalcon_sense/libfalcon AS_UTL/libbacktrace/posix.c
gcc -o /gwfefs/home/genome99/canu_git/canu/Linux-amd64/obj/libcanu.a/AS_UTL/libbacktrace/print.o -c -MD -I/gwfefs/home/genome99/canu_git/canu/src -IAS_UTL -Istores -Istores/libsnappy -Ialignment -Iutgcns/libNDalign -Iutgcns/libcns -Iutgcns/libpbutgcns -Iutgcns/libNDFalcon -Iutgcns/libboost -Imeryl/libleaff -IoverlapInCore -IoverlapInCore/libedlib -IoverlapInCore/liboverlap -Ifalcon_sense/libfalcon AS_UTL/libbacktrace/print.c
gcc -o /gwfefs/home/genome99/canu_git/canu/Linux-amd64/obj/libcanu.a/AS_UTL/libbacktrace/simple.o -c -MD -I/gwfefs/home/genome99/canu_git/canu/src -IAS_UTL -Istores -Istores/libsnappy -Ialignment -Iutgcns/libNDalign -Iutgcns/libcns -Iutgcns/libpbutgcns -Iutgcns/libNDFalcon -Iutgcns/libboost -Imeryl/libleaff -IoverlapInCore -IoverlapInCore/libedlib -IoverlapInCore/liboverlap -Ifalcon_sense/libfalcon AS_UTL/libbacktrace/simple.c
AS_UTL/libbacktrace/fileline.c: In function ‘fileline_initialize’:
AS_UTL/libbacktrace/fileline.c:64: error: ‘__ATOMIC_ACQUIRE’ undeclared (first use in this function)
AS_UTL/libbacktrace/fileline.c:64: error: (Each undeclared identifier is reported only once
AS_UTL/libbacktrace/fileline.c:64: error: for each function it appears in.)
AS_UTL/libbacktrace/fileline.c:146: error: ‘__ATOMIC_RELEASE’ undeclared (first use in this function)
AS_UTL/libbacktrace/dwarf.c: In function ‘dwarf_lookup_pc’:
AS_UTL/libbacktrace/dwarf.c:2779: error: ‘__ATOMIC_ACQUIRE’ undeclared (first use in this function)
AS_UTL/libbacktrace/dwarf.c:2779: error: (Each undeclared identifier is reported only once
AS_UTL/libbacktrace/dwarf.c:2779: error: for each function it appears in.)
AS_UTL/libbacktrace/dwarf.c:2839: error: ‘__ATOMIC_RELEASE’ undeclared (first use in this function)
AS_UTL/libbacktrace/dwarf.c: In function ‘dwarf_fileline’:
AS_UTL/libbacktrace/dwarf.c:2974: error: ‘__ATOMIC_ACQUIRE’ undeclared (first use in this function)
AS_UTL/libbacktrace/dwarf.c: In function ‘backtrace_dwarf_add’:
AS_UTL/libbacktrace/dwarf.c:3107: error: ‘__ATOMIC_ACQUIRE’ undeclared (first use in this function)
make: *** [/gwfefs/home/genome99/canu_git/canu/Linux-amd64/obj/libcanu.a/AS_UTL/libbacktrace/fileline.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [/gwfefs/home/genome99/canu_git/canu/Linux-amd64/obj/libcanu.a/AS_UTL/libbacktrace/dwarf.o] Error 1
AS_UTL/libbacktrace/elf.c: In function ‘elf_add_syminfo_data’:
AS_UTL/libbacktrace/elf.c:450: error: ‘__ATOMIC_ACQUIRE’ undeclared (first use in this function)
AS_UTL/libbacktrace/elf.c:450: error: (Each undeclared identifier is reported only once
AS_UTL/libbacktrace/elf.c:450: error: for each function it appears in.)
AS_UTL/libbacktrace/elf.c: In function ‘elf_syminfo’:
AS_UTL/libbacktrace/elf.c:495: error: ‘__ATOMIC_ACQUIRE’ undeclared (first use in this function)
AS_UTL/libbacktrace/elf.c: In function ‘backtrace_initialize’:
AS_UTL/libbacktrace/elf.c:960: error: ‘__ATOMIC_RELEASE’ undeclared (first use in this function)
AS_UTL/libbacktrace/elf.c:975: error: ‘__ATOMIC_ACQUIRE’ undeclared (first use in this function)
make: *** [/gwfefs/home/genome99/canu_git/canu/Linux-amd64/obj/libcanu.a/AS_UTL/libbacktrace/elf.o] Error 1
Building snapshot v1.4 (+180 changes) r8175 63e2ea3683e433e880da51a8911793b88217a519 (sync'd with guthub)

**Comment by brianwalenz** [comment]
That was perfect!

Please do two things:

1)  Build with `make BUILDSTACKTRACE=0`.  This should disable the problematic code (which just supplies information useful in bug reports).

2)  Then, try to install a more recent version of gcc.  I use gcc 4.8.5 and 4.9.4.

I want to see if BUILDSTACKTRACE actually solves the problem, but also want you to not use such an old compiler.  I wouldn't be surprised if other things break, especially when running the code.

**Comment by amit4mchiba** [comment]
Thanks for your reply. I tried "make BUILDSTACKTRACE=0" but it does not work.
I think it should be the old GCC that is causing this issue. The problem is that i am not allowed to upgrade gcc on my system. I followed these two appraoches to install gcc locally, but does work either-
1. http://openwall.info/wiki/internal/gcc-local-build (only that i tried to build gcc 4.8.5 instead of 4.5.0 as suggested in this blog)
2. https://www.gnu.org/software/gsrc/

I am now not sure if there is any way i may install canu. Is there any possibility?

**Comment by skoren** [comment]
Have you tried the binary release rather than building?

**Comment by indiancinema** [comment]
Not the OP but I am facing the same issue installing the latest canu from the repo. I am on GCC 5.3.0 and this the error I get from `make BUILDSTACKTRACE=0`

```
/software/builds/canu/gcc/64/1.4.2/canu-master/Linux-amd64/bin/libcanu.a(AS_UTL_stackTrace.o): In function `AS_UTL_catchCrash(int, siginfo*, void*)':
AS_UTL_stackTrace.C:(.text+0xa9): undefined reference to `backtrace_full'
/software/builds/canu/gcc/64/1.4.2/canu-master/Linux-amd64/bin/libcanu.a(AS_UTL_stackTrace.o): In function `AS_UTL_installCrashCatcher(char const*)':
AS_UTL_stackTrace.C:(.text+0x186): undefined reference to `backtrace_create_state'
collect2: ld returned 1 exit status
```

**Comment by brianwalenz** [comment]
Both @amit4mchiba and @indiancinema - I think you have half the compilation with stack trace support, and the other half without.  Try removing the Linux-amd64 directory and rebuilding with BUILDSTACKTRACE=0.  I was able to build with gcc 4.4.7.

**Comment by indiancinema** [comment]
Thanks, that worked.
